// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutohideController from "./autohide_controller"
application.register("autohide", AutohideController)

import FormController from "./form_controller"
application.register("form", FormController)

import InputValidationController from "./input_validation_controller"
application.register("input-validation", InputValidationController)

import ShowhideController from "./showhide_controller"
application.register("showhide", ShowhideController)
