services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"
    volumes:
      - .:/code
      - ./docker/database.yml:/code/config/database.yml
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - db
      - frontend
  db:
    image: postgres:15.1-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  frontend:
    build: .
    command: bash -c "foreman start -f docker/Procfile_docker.dev"
    stdin_open: true
    tty: true
